/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.blazartech.yahtzee;

import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author scott
 */
public class MainWindow extends JFrame {

    /**
     * Creates new form MainWindow
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws javax.swing.UnsupportedLookAndFeelException
     * @throws java.lang.IllegalAccessException
     */
    public MainWindow() throws ClassNotFoundException, InstantiationException, UnsupportedLookAndFeelException, IllegalAccessException {
        LookAndFeelInfo[] lafs = UIManager.getInstalledLookAndFeels();
        for (LookAndFeelInfo i : lafs) {
            if (i.getName().equals("Nimbus")) {
                UIManager.setLookAndFeel(i.getClassName());
            }
        }

        initComponents();
        
        scoreCard1.setGameDice(gameDice1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameDice1 = new com.blazartech.yahtzee.GameDice();
        scoreCard1 = new com.blazartech.yahtzee.ScoreCard();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Yahtzee!");
        getContentPane().add(gameDice1, java.awt.BorderLayout.NORTH);
        getContentPane().add(scoreCard1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.blazartech.yahtzee.GameDice gameDice1;
    private com.blazartech.yahtzee.ScoreCard scoreCard1;
    // End of variables declaration//GEN-END:variables
}
